---
title: Minimal Mistakes
timezone: America/New_York
collections:
  docs:
    title: Docs
    output: true
    permalink: "/:collection/:path/"
  pets:
    title: Pets
    output: true
    permalink: "/:collection/:path/"
  portfolio:
    title: Portfolio
    output: true
    permalink: "/:collection/:path/"
  posts:
    title: Posts
    output: true
  recipes:
    title: Recipes
    output: true
    permalink: "/:collection/:path/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: single
    author_profile: true
    read_time: true
    comments: true
    share: true
    related: true
- scope:
    path: ''
    type: pages
  values:
    layout: single
    author_profile: true
- scope:
    path: ''
    type: docs
  values:
    layout: single
    read_time: false
    author_profile: false
    share: false
    comments: false
    sidebar:
      nav: docs
- scope:
    path: ''
    type: recipes
  values:
    layout: single
    author_profile: true
    share: true
    comments: true
- scope:
    path: ''
    type: pets
  values:
    layout: single
    author_profile: true
    share: true
    comment: true
- scope:
    path: ''
    type: portfolio
  values:
    layout: single
    author_profile: false
    share: true
locale: en-US
title_separator: "-"
name: Michael Rose
description: A flexible Jekyll theme for your blog or site with a minimalist aesthetic.
url: https://mmistakes.github.io
baseurl: "/minimal-mistakes"
repository: mmistakes/minimal-mistakes
teaser: 
words_per_minute: 200
comments:
  provider: staticman
  disqus:
    shortname: 
  discourse:
    server: 
  facebook:
    appid: 
    num_posts: 
    colorscheme: 
staticman:
  allowedFields:
  - name
  - email
  - url
  - message
  branch: master
  commitMessage: New comment.
  filename: comment-{@timestamp}
  format: yml
  moderation: true
  path: _data/comments/{options.slug}
  requiredFields:
  - name
  - email
  - message
  transforms:
    email: md5
  generatedFields:
    date:
      type: date
      options:
        format: iso8601
atom_feed:
  path: 
google_site_verification: UQj93ERU9zgECodaaXgVpkjrFn9UrDMEzVamacSoQ8Y
bing_site_verification: 
alexa_site_verification: 
yandex_site_verification: 
twitter:
  username: mmistakes
facebook:
  username: michaelrose
  app_id: 
  publisher: 
og_image: "/assets/images/site-logo.png"
social:
  type: 
  name: 
  links:
  - https://twitter.com/mmistakes
  - https://facebook.com/michaelrose
analytics:
  provider: google-universal
  google:
    tracking_id: UA-2011187-3
author:
  name: Michael Rose
  avatar: "/assets/images/michael-rose.jpg"
  bio: Just another boring, tattooed, time traveling, designer.
  location: Buffalo, NY
  email: 
  uri: https://mademistakes.com
  bitbucket: 
  codepen: 
  dribbble: 
  flickr: 
  facebook: michaelrose
  foursquare: 
  github: mmistakes
  google_plus: 
  keybase: 
  instagram: mmistakes
  lastfm: 
  linkedin: 
  pinterest: 
  soundcloud: 
  stackoverflow: 
  steam: 
  tumblr: 
  twitter: mmistakes
  vine: 
  weibo: 
  xing: 
  youtube: 
include:
- ".htaccess"
- _pages
exclude:
- "*.sublime-project"
- "*.sublime-workspace"
- vendor
- ".asset-cache"
- ".bundle"
- ".jekyll-assets-cache"
- ".sass-cache"
- assets/js/plugins
- assets/js/_main.js
- assets/js/vendor
- Capfile
- CHANGELOG
- config
- Gemfile
- Gruntfile.js
- gulpfile.js
- LICENSE
- log
- node_modules
- package.json
- Rakefile
- README
- tmp
keep_files:
- ".git"
- ".svn"
encoding: utf-8
markdown_ext: markdown,mkdown,mkdn,mkd,md
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
sass:
  sass_dir: _sass
  style: compressed
permalink: "/:categories/:title/"
gems:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
whitelist:
- jekyll-paginate
- jekyll-sitemap
- jekyll-gist
- jekyll-feed
- jemoji
category_archive:
  type: liquid
  path: "/categories/"
tag_archive:
  type: liquid
  path: "/tags/"
compress_html:
  clippings: all
  ignore:
    envs: development
